### ISSUE TITLE
Maquetación Modal Hamburguesas 

### ISSUE THREAD

**Issue by ceciliaGeraldo** [nataliabarriga/SCL011-Burger-Queen#22]
Maquetar modal HTML & CSS con las opciones de las proteínas de la hamburguesa. 
Este modal va sobre la vista de almuerzo según figma.

**Comment by nataliabarriga** [comment]
Maquetación hecha y subida a la rama feat/estructuraHTML en carpeta "Estructura HTML" que contiene los archivos, modal.html y modal.css
