### ISSUE TITLE
Prototipo de baja fidelidad

### ISSUE THREAD

**Issue by ceciliaGeraldo** [nataliabarriga/SCL011-Burger-Queen#8]
Prototipo de baja fidelidad, hecho con la estructura visual básica del proyecto. Posiciones de elementos y planteamiento de vistas.

**Comment by nataliabarriga** [comment]
Realizado prototipo de pantalla de mesero https://www.figma.com/file/Fa8W3RFL2lIMbY4tfYybg4/Burguer-Queen?node-id=0%3A1

**Comment by nataliabarriga** [comment]
Realizado prototipo de pantalla cocinero y pantalla de inicio 
https://www.figma.com/file/Fa8W3RFL2lIMbY4tfYybg4/Burguer-Queen?node-id=0%3A1
