### ISSUE TITLE
Prototipo de alta fidelidad

### ISSUE THREAD

**Issue by ceciliaGeraldo** [nataliabarriga/SCL011-Burger-Queen#9]
Prototipo final realizado en Figma, con paleta de colores y todas las vistas definidas.

**Comment by nataliabarriga** [comment]
Realizado prototipo de alta casi completo. Faltan iteraciones post testeos para afinar detalles.
https://www.figma.com/file/Fa8W3RFL2lIMbY4tfYybg4/Burguer-Queen?node-id=38%3A2
